### ISSUE TITLE
Image Hosting

### ISSUE THREAD

**Issue by jbr** [mikepkes/txtifier#1]
This issue is intended as a starting place for discussion of adding image hosting.

Questions:
* How many images / how big?
* Where will this app be hosted when there's a read-only version? Asking in order to figure out if something like s3 is an option
* What do you imagine the image upload flow to be like? I'm not familiar with the foia data — does it have attached images in the xlsx file somehow? Or are they included separately and would have to be manually inserted?

**Comment by mikepkes** [comment]
Images are attached as a zip file, I believe they have folders inside the zip that correspond to the message number, to be confirmed.

**Comment by mikepkes** [comment]
<img width="546" alt="Screen Shot 2020-08-19 at 9 26 09 PM" src="https://user-images.githubusercontent.com/1572121/90716801-a3bd8380-e262-11ea-9538-3561a4f72757.png">

Resolved, hosting locally.
